api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : src
env_make : ~
env_prep : get-composer
env_post : ci-coveralls,ci-codacy
php_conf : timezone
php_exts : igbinary,memcached
app_prep : dep-composer
app_post : ~
app_path : bin/file-uploader
pkg_name : file-uploader-bundle
pkg_desc : "a bundle to help implement Blueimp's multi-file upload functionality in Symfony."
pkg_bndl : true
