---

s.file_uploader_file_url:
    path     :  /file/get/{fileId}
    defaults :
        _controller: s.file_uploader.manager.controller:getFileAction

s.file_uploader_file_delete:
    path     :  /file/delete/{fileId}/{fileName}
    defaults :
        _controller: s.file_uploader.manager.controller:deleteFileAction

s.file_uploader_filesystem_url:
    path     :  /file/get/{fileId}
    defaults :
        _controller: s.file_uploader.manager.controller:getFilesyetemFileAction

s.file_uploader_filesystem_delete:
    path     :  /file/delete/{fileName}
    defaults :
        _controller: s.file_uploader.manager.controller:deleteFilesystemFileAction
    requirements:
        relative_path: .+

...
