parameters:

    # component helper
    s.file_uploader.helper_utils.class:       Scribe\FileUploaderBundle\Component\FileUploaderHelper

    # file receiver
    s.file_uploader.document_receiver.class:  Scribe\FileUploaderBundle\Component\FileUploaderReceiver

    # upload manager
    s.file_uploader.manager.controller.class: Scribe\FileUploaderBundle\Controller\ManagerController

    # uploader doctrine entity/repo
    s.file_uploader.document.repo.class:      Scribe\FileUploaderBundle\Entity\FileUploaderDocumentRepository
    s.file_uploader.document.entity.class:    Scribe\FileUploaderBundle\Entity\FileUploaderDocument

services:
    s.file_uploader.helper_utils:
        class     : %s.file_uploader.helper_utils.class%
        arguments :
            - '@session'
            - '@service_container'

    s.file_uploader.document_receiver:
        class     : %s.file_uploader.document_receiver.class%
        arguments :
            - '@service_container'

    s.file_uploader.manager.controller:
        class     : %s.file_uploader.manager.controller.class%
        arguments :
            - '@s.file_uploader.document.repo'

    s.file_uploader.document.repo:
        class           : %s.file_uploader.document.repo.class%
        factory :
            - '@doctrine'
            - getRepository
        arguments:
            - %s.file_uploader.document.entity.class%
