Scribe\FileUploaderBundle\Entity\FileUploaderDocument:
    type: entity
    table: null
    repositoryClass: Scribe\FileUploaderBundle\Entity\FileUploaderDocumentRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '240'
        editId:
            type: string
            length: '240'
        size:
            type: integer
        file:
            type: blob
        mimeType:
            type: string
            length: '240'
        extension:
            type: string
            length: '20'
    lifecycleCallbacks: {  }
